### ISSUE TITLE
<Plug>(vimpire_eval) doesn't capture stdout

### ISSUE THREAD

**Issue by SevereOverfl0w** [kotarak/vimpire#1]
With `nmap cp <Plug>(vimpire_eval)` and vim-sexp (these are irrelevant, just convenient for repro).

Running `cpaF` on `(println 1)` in a buffer, doesn't capture stdout to the result buffer.

My expectation is that this information isn't lost. One solution is to capture and prefix `*out*` with `;`.

**Comment by kotarak** [comment]
Fixed with 6eac7671dd9ce73130950feffedc0f1eb7eddb00 and 6eac7671dd9ce73130950feffedc0f1eb7eddb00.

Output to `*out*` and `*err*` are captured and presented in the result buffer as comments. Followed by the printed value of the evaluated form. Multiple forms (and possible output) are printed one after the other as if they were pasted into a repl. Also `*out*` and `*err*` are merged as their output is received from the repl. Again, just like it would look like in a normal terminal repl.
